version: "3.8"

networks:
  enterprise-net:
    driver: bridge

services:

  backend:
    build: ./backend
    container_name: enterprise-backend
    ports:
      - "8602:8602"
    networks:
      - enterprise-net

  frontend:
    build: ./frontend
    container_name: enterprise-frontend
    ports:
      - "8702:80"
    depends_on:
      - backend
    networks:
      - enterprise-net

  proxy:
    image: nginx:alpine
    container_name: enterprise-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8601:80"
    depends_on:
      - frontend
      - backend
    networks:
      - enterprise-net

  prometheus:
    image: prom/prometheus
    container_name: enterprise-prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - enterprise-net

  grafana:
    image: grafana/grafana
    container_name: enterprise-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - enterprise-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: enterprise-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - enterprise-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: enterprise-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://enterprise-elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - enterprise-net
